import type { Category } from "./types";

export const CATEGORIES: Category[] = [
  { id: "trending-movie", label: "Trending Movies", slug: "trending-movies", type: "movie", endpoint: "trending" },
  { id: "trending-tv", label: "Trending TV Series", slug: "trending-tv", type: "tv", endpoint: "trending" },
  // Regional categories — placed prominently near the top
  { id: "pakistani", label: "Pakistani Movies & Dramas", slug: "pakistani-movies-dramas", type: "movie", endpoint: "discover", withOriginalLanguage: "ur", withOriginCountry: "PK" },
  { id: "indian", label: "Indian Movies & Series", slug: "indian-movies-series", type: "movie", endpoint: "discover", withOriginalLanguage: "hi", withOriginCountry: "IN" },
  { id: "action", label: "Action", slug: "action", type: "movie", endpoint: "genre", genreId: 28 },
  { id: "scifi", label: "Sci-Fi", slug: "sci-fi", type: "movie", endpoint: "genre", genreId: 878 },
  { id: "marvel", label: "Marvel", slug: "marvel", type: "movie", endpoint: "discover", withCompanies: "420" },
  { id: "dc", label: "DC", slug: "dc", type: "movie", endpoint: "discover", withCompanies: "9993,128" },
  { id: "horror", label: "Horror", slug: "horror", type: "movie", endpoint: "genre", genreId: 27 },
  { id: "romance", label: "Romance", slug: "romance", type: "movie", endpoint: "genre", genreId: 10749 },
  { id: "thriller", label: "Thriller", slug: "thriller", type: "movie", endpoint: "genre", genreId: 53 },
  { id: "comedy", label: "Comedy", slug: "comedy", type: "movie", endpoint: "genre", genreId: 35 },
  { id: "standup", label: "Stand-up Comedy", slug: "stand-up-comedy", type: "movie", endpoint: "genre", genreId: 35 },
  { id: "martial", label: "Martial Arts", slug: "martial-arts", type: "movie", endpoint: "discover", withKeywords: "6090" },
  { id: "superheroes", label: "Superheroes", slug: "superheroes", type: "movie", endpoint: "genre", genreId: 14 },
  { id: "cyberpunk", label: "Cyberpunk", slug: "cyberpunk", type: "movie", endpoint: "discover", withKeywords: "209814" },
  { id: "fantasy", label: "Fantasy", slug: "fantasy", type: "movie", endpoint: "genre", genreId: 14 },
  { id: "animation-movie", label: "Animated Movies", slug: "animated-movies", type: "movie", endpoint: "genre", genreId: 16 },
  { id: "war", label: "War", slug: "war", type: "movie", endpoint: "genre", genreId: 10752 },
  { id: "crime", label: "Crime", slug: "crime", type: "movie", endpoint: "genre", genreId: 80 },
  { id: "documentary", label: "Documentary", slug: "documentary", type: "movie", endpoint: "genre", genreId: 99 },
  { id: "history", label: "History", slug: "history", type: "movie", endpoint: "genre", genreId: 36 },
  { id: "mystery", label: "Mystery", slug: "mystery", type: "movie", endpoint: "genre", genreId: 9648 },
  { id: "western", label: "Western", slug: "western", type: "movie", endpoint: "genre", genreId: 37 },
  { id: "family", label: "Family", slug: "family", type: "movie", endpoint: "genre", genreId: 10751 },
  { id: "anime", label: "Anime", slug: "anime", type: "tv", endpoint: "search", query: "anime" },
  { id: "cartoons", label: "Cartoons", slug: "cartoons", type: "tv", endpoint: "search", query: "cartoon" },
  { id: "boboiboy", label: "BoBoiBoy", slug: "boboiboy", type: "tv", endpoint: "search", query: "BoBoiBoy" },
  { id: "ben10", label: "Ben 10", slug: "ben-10", type: "tv", endpoint: "search", query: "Ben 10" },
  { id: "kdrama", label: "Korean Drama", slug: "korean-drama", type: "tv", endpoint: "search", query: "Korean drama" },
  { id: "action-tv", label: "Action & Adventure TV", slug: "action-tv", type: "tv", endpoint: "genre", genreId: 10759 },
  { id: "scifi-tv", label: "Sci-Fi & Fantasy TV", slug: "scifi-tv", type: "tv", endpoint: "genre", genreId: 10765 },
  { id: "crime-tv", label: "Crime TV", slug: "crime-tv", type: "tv", endpoint: "genre", genreId: 80 },
  { id: "comedy-tv", label: "Comedy TV", slug: "comedy-tv", type: "tv", endpoint: "genre", genreId: 35 },
  { id: "animation-tv", label: "Animation TV", slug: "animation-tv", type: "tv", endpoint: "genre", genreId: 16 },
  { id: "reality-tv", label: "Reality TV", slug: "reality-tv", type: "tv", endpoint: "genre", genreId: 10764 },
  { id: "documentary-tv", label: "Documentary TV", slug: "documentary-tv", type: "tv", endpoint: "genre", genreId: 99 },
];
